#define COMPONENT manticorefaction
#define COMPONENT_BEAUTIFIED manticorefaction
#include "\x\\addons\main\script_mod.hpp"
// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS
#ifdef DEBUG_ENABLED_MANTICOREFACTION
#define DEBUG_MODE_FULL
#endif
#ifdef DEBUG_SETTINGS_MANTICOREFACTION
#define DEBUG_SETTINGS DEBUG_SETTINGS_MANTICOREFACTION
#endif