//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 184.144923 on Stable branch
// Generated with ALiVE version 1.8.0.1808241
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class Manticore_Faction {
        displayName = "Manticore";
        side = 1;
        flag = "";
        icon = "";
        priority = 3;
    };
};